<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MovementsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('movements')->delete();
        
        \DB::table('movements')->insert(array (
            0 => 
            array (
                'id' => 1,
                'product_id' => 9,
                'type' => 'entrada',
                'quantity' => '171.00',
                'user_id' => 3,
                'description' => NULL,
                'created_at' => '2026-06-08 11:00:00',
                'updated_at' => '2026-07-19 00:18:04',
                'order_detail_id' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'product_id' => 13,
                'type' => 'salida',
                'quantity' => '100.00',
                'user_id' => 3,
                'description' => NULL,
                'created_at' => '2026-06-10 10:00:00',
                'updated_at' => '2026-07-19 00:18:04',
                'order_detail_id' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'product_id' => 5,
                'type' => 'entrada',
                'quantity' => '99.00',
                'user_id' => 3,
                'description' => NULL,
                'created_at' => '2026-06-11 08:00:00',
                'updated_at' => '2026-07-19 00:18:04',
                'order_detail_id' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'product_id' => 8,
                'type' => 'salida',
                'quantity' => '200.00',
                'user_id' => 2,
                'description' => NULL,
                'created_at' => '2026-06-09 09:00:00',
                'updated_at' => '2026-07-19 00:18:04',
                'order_detail_id' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'product_id' => 6,
                'type' => 'salida',
                'quantity' => '61.00',
                'user_id' => 1,
                'description' => NULL,
                'created_at' => '2026-06-20 13:00:00',
                'updated_at' => '2026-07-19 00:18:04',
                'order_detail_id' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'product_id' => 4,
                'type' => 'entrada',
                'quantity' => '72.00',
                'user_id' => 3,
                'description' => NULL,
                'created_at' => '2026-06-16 18:00:00',
                'updated_at' => '2026-07-19 00:18:04',
                'order_detail_id' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'product_id' => 4,
                'type' => 'entrada',
                'quantity' => '8.00',
                'user_id' => 1,
                'description' => NULL,
                'created_at' => '2026-06-17 18:00:00',
                'updated_at' => '2026-07-19 00:18:04',
                'order_detail_id' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'product_id' => 5,
                'type' => 'salida',
                'quantity' => '12.00',
                'user_id' => 2,
                'description' => NULL,
                'created_at' => '2026-06-16 09:00:00',
                'updated_at' => '2026-07-19 00:18:04',
                'order_detail_id' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'product_id' => 9,
                'type' => 'entrada',
                'quantity' => '145.00',
                'user_id' => 2,
                'description' => NULL,
                'created_at' => '2026-06-16 16:00:00',
                'updated_at' => '2026-07-19 00:18:04',
                'order_detail_id' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'product_id' => 13,
                'type' => 'entrada',
                'quantity' => '152.00',
                'user_id' => 1,
                'description' => NULL,
                'created_at' => '2026-06-27 14:00:00',
                'updated_at' => '2026-07-19 00:18:04',
                'order_detail_id' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'product_id' => 6,
                'type' => 'salida',
                'quantity' => '113.00',
                'user_id' => 2,
                'description' => NULL,
                'created_at' => '2026-06-28 18:00:00',
                'updated_at' => '2026-07-19 00:18:04',
                'order_detail_id' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'product_id' => 2,
                'type' => 'salida',
                'quantity' => '50.00',
                'user_id' => 3,
                'description' => NULL,
                'created_at' => '2026-06-26 11:00:00',
                'updated_at' => '2026-07-19 00:18:04',
                'order_detail_id' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'product_id' => 8,
                'type' => 'entrada',
                'quantity' => '66.00',
                'user_id' => 2,
                'description' => NULL,
                'created_at' => '2026-06-25 15:00:00',
                'updated_at' => '2026-07-19 00:18:04',
                'order_detail_id' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'product_id' => 11,
                'type' => 'entrada',
                'quantity' => '99.00',
                'user_id' => 1,
                'description' => NULL,
                'created_at' => '2026-06-22 10:00:00',
                'updated_at' => '2026-07-19 00:18:04',
                'order_detail_id' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'product_id' => 6,
                'type' => 'salida',
                'quantity' => '52.00',
                'user_id' => 2,
                'description' => NULL,
                'created_at' => '2026-07-02 13:00:00',
                'updated_at' => '2026-07-19 00:18:04',
                'order_detail_id' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'product_id' => 13,
                'type' => 'salida',
                'quantity' => '170.00',
                'user_id' => 3,
                'description' => NULL,
                'created_at' => '2026-06-29 11:00:00',
                'updated_at' => '2026-07-19 00:18:04',
                'order_detail_id' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'product_id' => 1,
                'type' => 'entrada',
                'quantity' => '73.00',
                'user_id' => 2,
                'description' => NULL,
                'created_at' => '2026-07-03 08:00:00',
                'updated_at' => '2026-07-19 00:18:04',
                'order_detail_id' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'product_id' => 6,
                'type' => 'salida',
                'quantity' => '192.00',
                'user_id' => 1,
                'description' => NULL,
                'created_at' => '2026-07-03 08:00:00',
                'updated_at' => '2026-07-19 00:18:04',
                'order_detail_id' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'product_id' => 4,
                'type' => 'salida',
                'quantity' => '192.00',
                'user_id' => 3,
                'description' => NULL,
                'created_at' => '2026-07-03 08:00:00',
                'updated_at' => '2026-07-19 00:18:04',
                'order_detail_id' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'product_id' => 6,
                'type' => 'entrada',
                'quantity' => '101.00',
                'user_id' => 1,
                'description' => NULL,
                'created_at' => '2026-07-12 08:00:00',
                'updated_at' => '2026-07-19 00:18:04',
                'order_detail_id' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'product_id' => 7,
                'type' => 'entrada',
                'quantity' => '180.00',
                'user_id' => 2,
                'description' => NULL,
                'created_at' => '2026-07-09 10:00:00',
                'updated_at' => '2026-07-19 00:18:04',
                'order_detail_id' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'product_id' => 8,
                'type' => 'salida',
                'quantity' => '21.00',
                'user_id' => 2,
                'description' => NULL,
                'created_at' => '2026-07-11 11:00:00',
                'updated_at' => '2026-07-19 00:18:04',
                'order_detail_id' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'product_id' => 4,
                'type' => 'salida',
                'quantity' => '122.00',
                'user_id' => 2,
                'description' => NULL,
                'created_at' => '2026-07-10 16:00:00',
                'updated_at' => '2026-07-19 00:18:04',
                'order_detail_id' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'product_id' => 7,
                'type' => 'salida',
                'quantity' => '100.00',
                'user_id' => 3,
                'description' => NULL,
                'created_at' => '2026-07-09 16:00:00',
                'updated_at' => '2026-07-19 00:18:04',
                'order_detail_id' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'product_id' => 4,
                'type' => 'salida',
                'quantity' => '98.00',
                'user_id' => 2,
                'description' => NULL,
                'created_at' => '2026-07-07 11:00:00',
                'updated_at' => '2026-07-19 00:18:04',
                'order_detail_id' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'product_id' => 7,
                'type' => 'entrada',
                'quantity' => '174.00',
                'user_id' => 3,
                'description' => NULL,
                'created_at' => '2026-07-17 16:00:00',
                'updated_at' => '2026-07-19 00:18:04',
                'order_detail_id' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'product_id' => 4,
                'type' => 'salida',
                'quantity' => '154.00',
                'user_id' => 3,
                'description' => NULL,
                'created_at' => '2026-07-14 09:00:00',
                'updated_at' => '2026-07-19 00:18:04',
                'order_detail_id' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'product_id' => 1,
                'type' => 'salida',
                'quantity' => '8.00',
                'user_id' => 3,
                'description' => NULL,
                'created_at' => '2026-07-18 11:00:00',
                'updated_at' => '2026-07-19 00:18:04',
                'order_detail_id' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'product_id' => 1,
                'type' => 'entrada',
                'quantity' => '128.00',
                'user_id' => 2,
                'description' => NULL,
                'created_at' => '2026-07-16 15:00:00',
                'updated_at' => '2026-07-19 00:18:04',
                'order_detail_id' => NULL,
            ),
            29 => 
            array (
                'id' => 50,
                'product_id' => 6,
                'type' => 'salida',
                'quantity' => '15.00',
                'user_id' => 5,
                'description' => 'Venta - Orden #22',
                'created_at' => '2026-07-26 03:58:57',
                'updated_at' => '2026-07-26 03:58:57',
                'order_detail_id' => 34,
            ),
            30 => 
            array (
                'id' => 51,
                'product_id' => 7,
                'type' => 'salida',
                'quantity' => '30.00',
                'user_id' => 5,
                'description' => 'Venta - Orden #22',
                'created_at' => '2026-07-26 03:58:57',
                'updated_at' => '2026-07-26 03:58:57',
                'order_detail_id' => 35,
            ),
            31 => 
            array (
                'id' => 52,
                'product_id' => 3,
                'type' => 'salida',
                'quantity' => '45.00',
                'user_id' => 5,
                'description' => 'Venta - Orden #22',
                'created_at' => '2026-07-26 03:58:57',
                'updated_at' => '2026-07-26 03:58:57',
                'order_detail_id' => 36,
            ),
            32 => 
            array (
                'id' => 62,
                'product_id' => 5,
                'type' => 'salida',
                'quantity' => '5.00',
                'user_id' => 5,
                'description' => 'Venta - Orden #23',
                'created_at' => '2026-08-11 21:05:45',
                'updated_at' => '2026-08-11 21:05:45',
                'order_detail_id' => 46,
            ),
            33 => 
            array (
                'id' => 63,
                'product_id' => 1,
                'type' => 'salida',
                'quantity' => '20.00',
                'user_id' => 5,
                'description' => 'Venta - Orden #1',
                'created_at' => '2026-08-11 21:06:19',
                'updated_at' => '2026-08-11 21:06:19',
                'order_detail_id' => 47,
            ),
            34 => 
            array (
                'id' => 64,
                'product_id' => 2,
                'type' => 'salida',
                'quantity' => '5.00',
                'user_id' => 5,
                'description' => 'Venta - Orden #1',
                'created_at' => '2026-08-11 21:06:19',
                'updated_at' => '2026-08-11 21:06:19',
                'order_detail_id' => 48,
            ),
            35 => 
            array (
                'id' => 65,
                'product_id' => 3,
                'type' => 'salida',
                'quantity' => '14.00',
                'user_id' => 5,
                'description' => 'Venta - Orden #2',
                'created_at' => '2026-08-11 21:07:03',
                'updated_at' => '2026-08-11 21:07:03',
                'order_detail_id' => 49,
            ),
            36 => 
            array (
                'id' => 66,
                'product_id' => 4,
                'type' => 'salida',
                'quantity' => '20.00',
                'user_id' => 5,
                'description' => 'Venta - Orden #2',
                'created_at' => '2026-08-11 21:07:03',
                'updated_at' => '2026-08-11 21:07:03',
                'order_detail_id' => 50,
            ),
            37 => 
            array (
                'id' => 67,
                'product_id' => 5,
                'type' => 'salida',
                'quantity' => '19.00',
                'user_id' => 5,
                'description' => 'Venta - Orden #3',
                'created_at' => '2026-08-11 21:07:27',
                'updated_at' => '2026-08-11 21:07:27',
                'order_detail_id' => 51,
            ),
            38 => 
            array (
                'id' => 68,
                'product_id' => 1,
                'type' => 'salida',
                'quantity' => '29.00',
                'user_id' => 5,
                'description' => 'Venta - Orden #4',
                'created_at' => '2026-08-11 21:08:51',
                'updated_at' => '2026-08-11 21:08:51',
                'order_detail_id' => 52,
            ),
            39 => 
            array (
                'id' => 69,
                'product_id' => 3,
                'type' => 'salida',
                'quantity' => '4.00',
                'user_id' => 5,
                'description' => 'Venta - Orden #4',
                'created_at' => '2026-08-11 21:08:51',
                'updated_at' => '2026-08-11 21:08:51',
                'order_detail_id' => 53,
            ),
            40 => 
            array (
                'id' => 71,
                'product_id' => 38,
                'type' => 'salida',
                'quantity' => '5.00',
                'user_id' => 5,
                'description' => 'Venta - Orden #6',
                'created_at' => '2026-08-11 21:10:17',
                'updated_at' => '2026-08-11 21:10:17',
                'order_detail_id' => 55,
            ),
            41 => 
            array (
                'id' => 72,
                'product_id' => 5,
                'type' => 'salida',
                'quantity' => '50.00',
                'user_id' => 5,
                'description' => 'Venta - Orden #7',
                'created_at' => '2026-08-11 21:12:07',
                'updated_at' => '2026-08-11 21:12:07',
                'order_detail_id' => 56,
            ),
            42 => 
            array (
                'id' => 74,
                'product_id' => 16,
                'type' => 'salida',
                'quantity' => '5.00',
                'user_id' => 5,
                'description' => 'Venta - Orden #8',
                'created_at' => '2026-08-11 21:12:43',
                'updated_at' => '2026-08-11 21:12:43',
                'order_detail_id' => 58,
            ),
            43 => 
            array (
                'id' => 75,
                'product_id' => 26,
                'type' => 'salida',
                'quantity' => '50.00',
                'user_id' => 5,
                'description' => 'Venta - Orden #9',
                'created_at' => '2026-08-11 21:14:17',
                'updated_at' => '2026-08-11 21:14:17',
                'order_detail_id' => 59,
            ),
            44 => 
            array (
                'id' => 76,
                'product_id' => 7,
                'type' => 'salida',
                'quantity' => '50.00',
                'user_id' => 5,
                'description' => 'Venta - Orden #10',
                'created_at' => '2026-08-11 21:16:35',
                'updated_at' => '2026-08-11 21:16:35',
                'order_detail_id' => 60,
            ),
            45 => 
            array (
                'id' => 77,
                'product_id' => 26,
                'type' => 'salida',
                'quantity' => '70.00',
                'user_id' => 5,
                'description' => 'Venta - Orden #10',
                'created_at' => '2026-08-11 21:16:35',
                'updated_at' => '2026-08-11 21:16:35',
                'order_detail_id' => 61,
            ),
            46 => 
            array (
                'id' => 78,
                'product_id' => 24,
                'type' => 'salida',
                'quantity' => '70.00',
                'user_id' => 5,
                'description' => 'Venta - Orden #11',
                'created_at' => '2026-08-11 21:17:36',
                'updated_at' => '2026-08-11 21:17:36',
                'order_detail_id' => 62,
            ),
            47 => 
            array (
                'id' => 79,
                'product_id' => 35,
                'type' => 'salida',
                'quantity' => '30.00',
                'user_id' => 5,
                'description' => 'Venta - Orden #12',
                'created_at' => '2026-08-11 21:18:08',
                'updated_at' => '2026-08-11 21:18:08',
                'order_detail_id' => 63,
            ),
            48 => 
            array (
                'id' => 80,
                'product_id' => 15,
                'type' => 'salida',
                'quantity' => '2.00',
                'user_id' => 5,
                'description' => 'Venta - Orden #13',
                'created_at' => '2026-08-11 21:18:48',
                'updated_at' => '2026-08-11 21:18:48',
                'order_detail_id' => 64,
            ),
            49 => 
            array (
                'id' => 81,
                'product_id' => 3,
                'type' => 'salida',
                'quantity' => '9.98',
                'user_id' => 5,
                'description' => 'Venta - Orden #14',
                'created_at' => '2026-08-11 21:19:17',
                'updated_at' => '2026-08-11 21:19:17',
                'order_detail_id' => 65,
            ),
            50 => 
            array (
                'id' => 82,
                'product_id' => 1,
                'type' => 'salida',
                'quantity' => '5.00',
                'user_id' => 5,
                'description' => 'Venta - Orden #15',
                'created_at' => '2026-08-11 21:19:41',
                'updated_at' => '2026-08-11 21:19:41',
                'order_detail_id' => 66,
            ),
            51 => 
            array (
                'id' => 83,
                'product_id' => 2,
                'type' => 'salida',
                'quantity' => '15.00',
                'user_id' => 5,
                'description' => 'Venta - Orden #15',
                'created_at' => '2026-08-11 21:19:41',
                'updated_at' => '2026-08-11 21:19:41',
                'order_detail_id' => 67,
            ),
            52 => 
            array (
                'id' => 84,
                'product_id' => 14,
                'type' => 'salida',
                'quantity' => '5.00',
                'user_id' => 5,
                'description' => 'Venta - Orden #16',
                'created_at' => '2026-08-11 21:20:16',
                'updated_at' => '2026-08-11 21:20:16',
                'order_detail_id' => 68,
            ),
            53 => 
            array (
                'id' => 85,
                'product_id' => 14,
                'type' => 'salida',
                'quantity' => '44.00',
                'user_id' => 5,
                'description' => 'Venta - Orden #17',
                'created_at' => '2026-08-11 21:21:40',
                'updated_at' => '2026-08-11 21:21:40',
                'order_detail_id' => 69,
            ),
            54 => 
            array (
                'id' => 87,
                'product_id' => 8,
                'type' => 'salida',
                'quantity' => '8.00',
                'user_id' => 5,
                'description' => 'Venta - Orden #19',
                'created_at' => '2026-08-11 21:23:00',
                'updated_at' => '2026-08-11 21:23:00',
                'order_detail_id' => 71,
            ),
            55 => 
            array (
                'id' => 88,
                'product_id' => 13,
                'type' => 'salida',
                'quantity' => '7.00',
                'user_id' => 5,
                'description' => 'Venta - Orden #19',
                'created_at' => '2026-08-11 21:23:00',
                'updated_at' => '2026-08-11 21:23:00',
                'order_detail_id' => 72,
            ),
            56 => 
            array (
                'id' => 89,
                'product_id' => 23,
                'type' => 'salida',
                'quantity' => '75.00',
                'user_id' => 5,
                'description' => 'Venta - Orden #18',
                'created_at' => '2026-08-11 21:23:22',
                'updated_at' => '2026-08-11 21:23:22',
                'order_detail_id' => 73,
            ),
            57 => 
            array (
                'id' => 90,
                'product_id' => 14,
                'type' => 'salida',
                'quantity' => '8.00',
                'user_id' => 5,
                'description' => 'Venta - Orden #20',
                'created_at' => '2026-08-11 21:23:41',
                'updated_at' => '2026-08-11 21:23:41',
                'order_detail_id' => 74,
            ),
            58 => 
            array (
                'id' => 91,
                'product_id' => 14,
                'type' => 'salida',
                'quantity' => '7.00',
                'user_id' => 5,
                'description' => 'Venta - Orden #21',
                'created_at' => '2026-08-11 21:24:15',
                'updated_at' => '2026-08-11 21:24:15',
                'order_detail_id' => 75,
            ),
            59 => 
            array (
                'id' => 93,
                'product_id' => 5,
                'type' => 'salida',
                'quantity' => '8.00',
                'user_id' => 5,
                'description' => 'Venta - Orden #24',
                'created_at' => '2026-08-11 21:25:26',
                'updated_at' => '2026-08-11 21:25:26',
                'order_detail_id' => 77,
            ),
            60 => 
            array (
                'id' => 95,
                'product_id' => 25,
                'type' => 'salida',
                'quantity' => '55.20',
                'user_id' => 5,
                'description' => 'Venta - Orden #25',
                'created_at' => '2026-08-11 21:26:31',
                'updated_at' => '2026-08-11 21:26:31',
                'order_detail_id' => 79,
            ),
            61 => 
            array (
                'id' => 96,
                'product_id' => 3,
                'type' => 'salida',
                'quantity' => '8.00',
                'user_id' => 5,
                'description' => 'Venta - Orden #26',
                'created_at' => '2026-08-11 21:26:53',
                'updated_at' => '2026-08-11 21:26:53',
                'order_detail_id' => 80,
            ),
            62 => 
            array (
                'id' => 97,
                'product_id' => 17,
                'type' => 'salida',
                'quantity' => '6.00',
                'user_id' => 5,
                'description' => 'Venta - Orden #26',
                'created_at' => '2026-08-11 21:26:53',
                'updated_at' => '2026-08-11 21:26:53',
                'order_detail_id' => 81,
            ),
            63 => 
            array (
                'id' => 104,
                'product_id' => 23,
                'type' => 'salida',
                'quantity' => '25.00',
                'user_id' => 1,
                'description' => 'Venta - Orden #27',
                'created_at' => '2026-08-24 20:36:18',
                'updated_at' => '2026-08-24 20:36:18',
                'order_detail_id' => 88,
            ),
            64 => 
            array (
                'id' => 105,
                'product_id' => 4,
                'type' => 'salida',
                'quantity' => '5.00',
                'user_id' => 1,
                'description' => 'Venta - Orden #27',
                'created_at' => '2026-08-24 20:36:18',
                'updated_at' => '2026-08-24 20:36:18',
                'order_detail_id' => 89,
            ),
            65 => 
            array (
                'id' => 107,
                'product_id' => 37,
                'type' => 'salida',
                'quantity' => '100.00',
                'user_id' => 2,
                'description' => 'Venta - Orden #33',
                'created_at' => '2026-08-24 20:44:39',
                'updated_at' => '2026-08-24 20:44:39',
                'order_detail_id' => 91,
            ),
            66 => 
            array (
                'id' => 108,
                'product_id' => 19,
                'type' => 'salida',
                'quantity' => '1.00',
                'user_id' => 2,
                'description' => 'Venta - Orden #33',
                'created_at' => '2026-08-24 20:44:39',
                'updated_at' => '2026-08-24 20:44:39',
                'order_detail_id' => 92,
            ),
        ));
        
        
    }
}